/* ══════════════════════════════════════════════════
   juegos-engine.js — Motor de juegos EduNovaOne
   Renderiza el área, selector de grado y juegos
   según data-area del #areaRoot en cada HTML.
   ══════════════════════════════════════════════════ */

// ── Puntos ──────────────────────────────────────────
const PUNTOS_KEY = 'enu_puntos_hoy';
function getPuntos() {
  try { const s = JSON.parse(localStorage.getItem(PUNTOS_KEY)||'{}'); return s.d === new Date().toDateString() ? (s.p||0) : 0; } catch { return 0; }
}
function addPuntos(n) {
  const p = getPuntos() + n;
  try { localStorage.setItem(PUNTOS_KEY, JSON.stringify({ d: new Date().toDateString(), p })); } catch {}
  const el = document.getElementById('totalPuntos');
  if (el) el.textContent = p;
}

// ══════════════════════════════════════════════════
// BANCO DE PREGUNTAS  (area → grado → preguntas[])
// ══════════════════════════════════════════════════
const BANCO = {
  matematica: {
    1: [
      { p: '¿Cuánto es el MCM de 4 y 6?', ops: ['8','12','24','6'], r: 1 },
      { p: '¿Qué fracción equivale a 1/2?', ops: ['2/3','3/6','3/4','4/6'], r: 1 },
      { p: '¿Cuánto es 3² + 4²?', ops: ['25','49','14','7'], r: 0 },
      { p: '¿Cuál es el MCD de 12 y 18?', ops: ['3','6','9','12'], r: 1 },
      { p: '¿Cuánto es −5 + 8?', ops: ['−3','3','13','−13'], r: 1 },
      { p: '¿Cuánto es el 25% de 80?', ops: ['20','25','16','40'], r: 0 },
      { p: '¿Cuántos metros hay en 3.5 km?', ops: ['350','3500','3050','35000'], r: 1 },
      { p: '¿Qué número es múltiplo de 7?', ops: ['22','35','41','50'], r: 1 },
      { p: '¿Cuánto es √144?', ops: ['11','12','13','14'], r: 1 },
      { p: '¿Cuánto es 2/3 + 1/3?', ops: ['3/6','1','2/6','3/3'], r: 1 },
    ],
    2: [
      { p: 'Si 2x + 4 = 10, ¿cuánto es x?', ops: ['2','3','4','5'], r: 1 },
      { p: '¿Cómo se expande (a+b)²?', ops: ['a²+b²','a²+ab+b²','a²+2ab+b²','2a+2b'], r: 2 },
      { p: 'Factoriza: x²−9', ops: ['(x−3)²','(x+3)(x−3)','(x+9)(x−1)','(x−9)(x+1)'], r: 1 },
      { p: 'Si 3x − 7 = 11, ¿cuánto es x?', ops: ['4','5','6','7'], r: 2 },
      { p: '¿Cuánto es (−3)²?', ops: ['−9','9','6','−6'], r: 1 },
      { p: 'Resuelve: x/2 = 6', ops: ['3','8','12','14'], r: 2 },
      { p: '¿Cuál es el grado del polinomio 4x³+2x?', ops: ['1','2','3','4'], r: 2 },
      { p: 'El coeficiente de 7x³ es:', ops: ['3','x','7','7x'], r: 2 },
      { p: '¿Qué valor cumple 5x = 0?', ops: ['1','−1','5','0'], r: 3 },
      { p: 'Simplifica: 2x + 3x', ops: ['5','5x','6x','2x³'], r: 1 },
    ],
    3: [
      { p: 'Catetos 3 y 4. ¿Hipotenusa?', ops: ['5','6','7','8'], r: 0 },
      { p: 'Suma de ángulos internos de un triángulo:', ops: ['90°','180°','270°','360°'], r: 1 },
      { p: '¿Cuánto es sen 30°?', ops: ['√3/2','1/2','1','√2/2'], r: 1 },
      { p: 'Área de triángulo con base 6 y altura 4:', ops: ['24','12','10','8'], r: 1 },
      { p: '¿Cuánto es cos 60°?', ops: ['1','√3/2','1/2','0'], r: 2 },
      { p: '¿Cuántos lados tiene un hexágono?', ops: ['5','6','7','8'], r: 1 },
      { p: 'Suma de ángulos de un cuadrilátero:', ops: ['180°','270°','360°','720°'], r: 2 },
      { p: 'tan θ = ?', ops: ['opuesto/hipotenusa','adyacente/hipotenusa','opuesto/adyacente','hipotenusa/opuesto'], r: 2 },
      { p: 'Perímetro de un cuadrado de lado 5:', ops: ['10','20','25','15'], r: 1 },
      { p: '¿Cuánto es tan 45°?', ops: ['0','√3','1','1/2'], r: 2 },
    ],
    4: [
      { p: 'f(x) = 2x + 1 en x=3 da:', ops: ['5','6','7','8'], r: 2 },
      { p: 'La media de 4, 7, 7, 9, 3 es:', ops: ['5','6','7','8'], r: 1 },
      { p: '¿Qué función genera una parábola?', ops: ['Lineal','Cuadrática','Exponencial','Constante'], r: 1 },
      { p: 'P(cara) al lanzar una moneda:', ops: ['1/3','1/4','1/2','2/3'], r: 2 },
      { p: 'La moda de 4, 7, 7, 9, 3 es:', ops: ['3','4','7','9'], r: 2 },
      { p: 'La mediana de 2, 4, 6, 8, 10 es:', ops: ['4','5','6','7'], r: 2 },
      { p: 'En f(x) = mx + b, "m" es:', ops: ['Ordenada','Pendiente','Dominio','Raíz'], r: 1 },
      { p: 'Resultados posibles al lanzar un dado:', ops: ['4','5','6','12'], r: 2 },
      { p: 'La varianza mide:', ops: ['El promedio','La dispersión','El más frecuente','El dato central'], r: 1 },
      { p: 'Una recta horizontal es una función:', ops: ['Lineal','Cuadrática','Constante','Exponencial'], r: 2 },
    ],
    5: [
      { p: "f(x) = 3x². ¿f'(x)?", ops: ['3x','6x','x²','6x²'], r: 1 },
      { p: '¿Qué mide la derivada?', ops: ['Área bajo la curva','Tasa de cambio instantánea','Máximo valor','Integral'], r: 1 },
      { p: '∫2x dx =', ops: ['x²','x²+C','2x²+C','x+C'], r: 1 },
      { p: 'Módulo del vector (3,4):', ops: ['5','7','12','6'], r: 0 },
      { p: 'lím(x→2) de x² es:', ops: ['2','3','4','8'], r: 2 },
      { p: 'Derivada de una constante:', ops: ['La misma','1','0','Indefinida'], r: 2 },
      { p: 'd/dx(xⁿ) =', ops: ['nxⁿ','nxⁿ⁻¹','xⁿ⁻¹','n·x'], r: 1 },
      { p: 'Matriz cuadrada tiene:', ops: ['Mismas filas y columnas','Solo una fila','Solo una columna','Diagonal con ceros'], r: 0 },
      { p: 'Producto de dos vectores ortogonales:', ops: ['1','−1','0','Indefinido'], r: 2 },
      { p: '∫₀¹ x dx =', ops: ['1','1/2','2','0'], r: 1 },
    ],
  },
  ciencia: {
    1: [
      { p: '¿Cuál es la unidad básica de la vida?', ops: ['El átomo','La célula','El tejido','El órgano'], r: 1 },
      { p: '¿Qué gas producen las plantas en fotosíntesis?', ops: ['CO₂','N₂','O₂','H₂'], r: 2 },
      { p: '¿Qué célula NO tiene núcleo?', ops: ['Animal','Vegetal','Procariota','Eucariota'], r: 2 },
      { p: '¿Qué organelo produce energía?', ops: ['Núcleo','Ribosoma','Mitocondria','Vacuola'], r: 2 },
      { p: 'La cadena alimenticia comienza con:', ops: ['Carnívoros','Herbívoros','Productores','Descomponedores'], r: 2 },
      { p: '¿Qué reino incluye a los hongos?', ops: ['Animalia','Plantae','Fungi','Monera'], r: 2 },
      { p: 'Un ecosistema incluye:', ops: ['Solo seres vivos','Solo el ambiente','Seres vivos y su entorno','Solo animales'], r: 2 },
      { p: '¿Qué proceso realiza la planta para producir alimento?', ops: ['Respiración','Fotosíntesis','Digestión','Excreción'], r: 1 },
      { p: 'Función del sistema circulatorio:', ops: ['Digerir alimentos','Transportar sangre','Filtrar aire','Producir hormonas'], r: 1 },
      { p: '¿Cuántos sistemas tiene el cuerpo humano aprox.?', ops: ['5','8','11','15'], r: 2 },
    ],
    2: [
      { p: '¿Cuántos protones tiene el oxígeno?', ops: ['6','7','8','9'], r: 2 },
      { p: '¿Qué representa el número atómico?', ops: ['Neutrones','Protones','Masa atómica','Electrones'], r: 1 },
      { p: 'Fórmula del agua:', ops: ['H₂O₂','CO₂','H₂O','NaCl'], r: 2 },
      { p: '¿Qué mide el pH?', ops: ['Temperatura','Acidez/basicidad','Presión','Densidad'], r: 1 },
      { p: 'Los gases nobles están en el grupo:', ops: ['1','2','17','18'], r: 3 },
      { p: '¿Qué es un enlace iónico?', ops: ['Compartir electrones','Transferencia de electrones','Unión de núcleos','Repulsión de cargas'], r: 1 },
      { p: 'Estado con forma y volumen fijos:', ops: ['Gas','Líquido','Sólido','Plasma'], r: 2 },
      { p: 'Símbolo del sodio:', ops: ['So','Na','Sn','Nd'], r: 1 },
      { p: '¿Qué reacción produce sal y agua?', ops: ['Oxidación','Reducción','Neutralización','Combustión'], r: 2 },
      { p: 'Balancea: H₂ + O₂ → H₂O. ¿Cuántas H₂O?', ops: ['1','2','3','4'], r: 1 },
    ],
    3: [
      { p: 'La Segunda Ley de Newton:', ops: ['Inercia','F = m × a','Acción y reacción','Conservación de energía'], r: 1 },
      { p: 'En MRU la velocidad es:', ops: ['Creciente','Decreciente','Constante','Cero'], r: 2 },
      { p: 'Energía cinética:', ops: ['E=mgh','F=ma','Ec=½mv²','W=Fd'], r: 2 },
      { p: '¿Qué tipo de onda es la luz?', ops: ['Mecánica','Longitudinal','Electromagnética','Sonora'], r: 2 },
      { p: 'Unidad de fuerza en el SI:', ops: ['Joule','Pascal','Newton','Watt'], r: 2 },
      { p: 'Velocidad v=20m/s, t=5s → d=', ops: ['4m','25m','100m','15m'], r: 2 },
      { p: 'Trabajo W =', ops: ['W=mv','W=F×d','W=½mv²','W=mgh'], r: 1 },
      { p: '"Acción-reacción" es la ___ Ley de Newton:', ops: ['Primera','Segunda','Tercera','Cuarta'], r: 2 },
      { p: 'Presión P =', ops: ['P=m×V','P=F/A','P=mgh','P=mv'], r: 1 },
      { p: 'La inercia corresponde a la ___ Ley de Newton:', ops: ['Primera','Segunda','Tercera','Cuarta'], r: 0 },
    ],
    4: [
      { p: 'Alcanos tienen fórmula:', ops: ['CₙH₂ₙ','CₙH₂ₙ₊₂','CₙH₂ₙ₋₂','CₙHₙ'], r: 1 },
      { p: '36 g de agua (M=18) son ___ mol:', ops: ['1','2','3','4'], r: 1 },
      { p: 'El reactivo limitante es:', ops: ['El que está en exceso','El que se agota primero','El de mayor masa','El más lento'], r: 1 },
      { p: 'Grupo funcional del alcohol:', ops: ['−COOH','−CHO','−OH','−NH₂'], r: 2 },
      { p: 'Un ácido libera en agua:', ops: ['OH⁻','H⁺','Na⁺','Cl⁻'], r: 1 },
      { p: 'Fórmula del metano:', ops: ['C₂H₆','CH₄','C₃H₈','C₂H₄'], r: 1 },
      { p: 'Los alquenos tienen enlace:', ops: ['Simple C−C','Doble C=C','Triple C≡C','Iónico'], r: 1 },
      { p: 'Rendimiento=18, teórico=20 → %:', ops: ['80%','85%','90%','95%'], r: 2 },
      { p: '¿Qué es la estequiometría?', ops: ['Estudio de la luz','Cálculo de cantidades en reacciones','Análisis de energía','Clasificación de elementos'], r: 1 },
      { p: 'Nomenclatura sistemática:', ops: ['Nombres comunes','IUPAC','Trivial','Empírica'], r: 1 },
    ],
    5: [
      { p: 'E = mc² es:', ops: ['Energía cinética','Energía potencial','Equivalencia masa-energía','Presión'], r: 2 },
      { p: '¿Cuántos planetas tiene el Sistema Solar?', ops: ['7','8','9','10'], r: 1 },
      { p: 'La fisión nuclear:', ops: ['Une núcleos ligeros','Divide núcleos pesados','Emite luz','Produce agua'], r: 1 },
      { p: 'Velocidad de la luz aprox.:', ops: ['3×10⁶ m/s','3×10⁸ m/s','3×10¹⁰ m/s','3×10⁴ m/s'], r: 1 },
      { p: 'Planetas interiores del Sistema Solar:', ops: ['Júpiter,Saturno,Urano,Neptuno','Mercurio,Venus,Tierra,Marte','Solo Tierra y Marte','Mercurio y Venus'], r: 1 },
      { p: 'Vida media es:', ops: ['Su edad','Tiempo en desintegrar la mitad','Tiempo de formación','Período orbital'], r: 1 },
      { p: '3ra Ley de Kepler relaciona:', ops: ['Masa y velocidad','T² con r³','Distancia y tiempo','Fuerza y aceleración'], r: 1 },
      { p: 'La relatividad especial la propuso:', ops: ['Newton','Darwin','Einstein','Bohr'], r: 2 },
      { p: 'La fusión nuclear:', ops: ['Divide átomos pesados','Une núcleos ligeros liberando energía','Es una reacción química','Produce radioactividad alfa'], r: 1 },
      { p: 'El año luz es medida de:', ops: ['Tiempo','Distancia','Velocidad','Masa'], r: 1 },
    ],
  },
  historia: {
    1: [
      { p: '¿Qué civilización construyó las pirámides de Giza?', ops: ['Griega','Romana','Egipcia','Mesopotámica'], r: 2 },
      { p: '¿Dónde surgió la escritura cuneiforme?', ops: ['Egipto','Grecia','Mesopotamia','China'], r: 2 },
      { p: '¿Cuántas regiones naturales tiene el Perú?', ops: ['2','3','4','5'], r: 1 },
      { p: 'La democracia fue inventada en:', ops: ['Roma','Atenas','Esparta','Cartago'], r: 1 },
      { p: '¿Qué río permitió el desarrollo de Egipto?', ops: ['Éufrates','Tigris','Nilo','Ganges'], r: 2 },
      { p: 'Las 8 regiones de Pulgar Vidal incluyen:', ops: ['Chala y Yunga','Playa y Montaña','Mar y Sierra','Selva y Costa'], r: 0 },
      { p: '¿Cuántos departamentos tiene el Perú?', ops: ['20','22','24','26'], r: 2 },
      { p: 'Roma fue fundada aprox. en:', ops: ['1000 a.C.','753 a.C.','500 a.C.','200 a.C.'], r: 1 },
      { p: 'Filósofo griego maestro de Alejandro Magno:', ops: ['Sócrates','Platón','Aristóteles','Pitágoras'], r: 2 },
      { p: 'Capital del Perú:', ops: ['Cusco','Arequipa','Lima','Trujillo'], r: 2 },
    ],
    2: [
      { p: 'Capital del Imperio Inca:', ops: ['Lima','Machu Picchu','Cusco','Cajamarca'], r: 2 },
      { p: '¿En qué año llegó Pizarro al Perú?', ops: ['1520','1525','1532','1540'], r: 2 },
      { p: '¿Cuántos suyos tenía el Tahuantinsuyo?', ops: ['2','3','4','5'], r: 2 },
      { p: 'Trabajo forzado en el Virreinato:', ops: ['Yanaconazgo','Mita','Encomienda','Tributo'], r: 1 },
      { p: 'El Virreinato del Perú fue creado en:', ops: ['1532','1542','1550','1600'], r: 1 },
      { p: '¿Quién fue el último inca?', ops: ['Huáscar','Atahualpa','Túpac Yupanqui','Pachacútec'], r: 1 },
      { p: 'Primer inca según la tradición:', ops: ['Atahualpa','Huáscar','Manco Cápac','Pachacútec'], r: 2 },
      { p: '¿En qué ciudad fue capturado Atahualpa?', ops: ['Cusco','Lima','Cajamarca','Trujillo'], r: 2 },
      { p: 'La plata de Potosí era del actual:', ops: ['Perú','Bolivia','Chile','Argentina'], r: 1 },
      { p: 'Nombre del gran imperio inca:', ops: ['Azteca','Maya','Tahuantinsuyo','Chimú'], r: 2 },
    ],
    3: [
      { p: '¿En qué año se proclamó la independencia del Perú?', ops: ['1810','1819','1821','1824'], r: 2 },
      { p: '¿Qué batalla consolidó la independencia?', ops: ['Junín','Ayacucho','Chacabuco','Pichincha'], r: 1 },
      { p: '¿Quién proclamó la independencia del Perú?', ops: ['Bolívar','San Martín','O\'Higgins','Sucre'], r: 1 },
      { p: 'Rebelión de Túpac Amaru II:', ops: ['1770','1780','1790','1800'], r: 1 },
      { p: 'Batalla de Ayacucho fue en:', ops: ['1821','1822','1823','1824'], r: 3 },
      { p: 'Causa externa de la independencia:', ops: ['Abusos coloniales','Revolución Francesa e independencia EE.UU.','Crisis económica local','Terremotos'], r: 1 },
      { p: 'Gobierno adoptado tras la independencia:', ops: ['Monarquía','República presidencialista','Teocracia','Oligarquía'], r: 1 },
      { p: 'La Guerra del Pacífico fue entre:', ops: ['Perú y Brasil','Perú,Bolivia y Chile','Perú y Ecuador','Perú y Colombia'], r: 1 },
      { p: 'Año de la independencia peruana:', ops: ['1819','1820','1821','1822'], r: 2 },
      { p: '¿Quién completó la independencia sudamericana?', ops: ['San Martín','Bolívar','Sucre','O\'Higgins'], r: 1 },
    ],
    4: [
      { p: '¿Cuándo se fundó el APRA?', ops: ['1920','1924','1930','1935'], r: 1 },
      { p: 'Reforma Agraria de Velasco:', ops: ['1965','1969','1975','1980'], r: 1 },
      { p: '¿Quién capturó a Abimael Guzmán?', ops: ['Fujimori','García','Belaúnde','Toledo'], r: 0 },
      { p: 'Guzmán fue capturado en:', ops: ['1990','1991','1992','1993'], r: 2 },
      { p: '"República Aristocrática" duró de 1895 a:', ops: ['1910','1915','1919','1925'], r: 2 },
      { p: '¿Cuándo comenzó Sendero Luminoso?', ops: ['1978','1980','1982','1985'], r: 1 },
      { p: 'Golpe que terminó el gobierno de Velasco:', ops: ['Elecciones','Morales Bermúdez','Renuncia','Muerte'], r: 1 },
      { p: 'El Oncenio de Leguía duró de 1919 a:', ops: ['1925','1928','1930','1933'], r: 2 },
      { p: 'Grupo terrorista junto a Sendero:', ops: ['FARC','ELN','MRTA','IRA'], r: 2 },
      { p: 'Velasco realizó la reforma:', ops: ['Educativa','Agraria','Electoral','Tributaria'], r: 1 },
    ],
    5: [
      { p: '¿Cuándo cayó el Muro de Berlín?', ops: ['1985','1987','1989','1991'], r: 2 },
      { p: '¿En qué año se disolvió la URSS?', ops: ['1989','1990','1991','1993'], r: 2 },
      { p: '¿Cuándo fue fundada la ONU?', ops: ['1939','1945','1948','1950'], r: 1 },
      { p: 'La Guerra Fría fue entre:', ops: ['EE.UU. y China','EE.UU. y Alemania','EE.UU. y URSS','EE.UU. y Japón'], r: 2 },
      { p: 'Perú en APEC pertenece al bloque:', ops: ['Europeo','Asia-Pacífico','Sudamericano','Africano'], r: 1 },
      { p: '¿Cuándo comenzó la 2da Guerra Mundial?', ops: ['1935','1937','1939','1941'], r: 2 },
      { p: 'La globalización integra:', ops: ['Solo países ricos','Economías y culturas a nivel mundial','Solo mercados financieros','Solo estados europeos'], r: 1 },
      { p: 'OEA: organización de estados:', ops: ['Europeos','Africanos','Americanos','Asiáticos'], r: 2 },
      { p: '¿Cuándo terminó la 2da Guerra Mundial?', ops: ['1943','1944','1945','1946'], r: 2 },
      { p: 'Alianza del Pacífico: Perú + Colombia + Chile +', ops: ['Brasil','Argentina','México','Ecuador'], r: 2 },
    ],
  },
  comunicacion: {
    1: [
      { p: '"Corre como el viento" es:', ops: ['Metáfora','Símil','Hipérbole','Personificación'], r: 1 },
      { p: 'Texto que cuenta una historia:', ops: ['Argumentativo','Instructivo','Narrativo','Descriptivo'], r: 2 },
      { p: 'La idea principal puede ser:', ops: ['Solo explícita','Solo implícita','Explícita o implícita','Siempre al final'], r: 2 },
      { p: '"Además" es conector de:', ops: ['Contraste','Causa','Adición','Consecuencia'], r: 2 },
      { p: 'Texto instructivo:', ops: ['Cuenta un cuento','Da pasos a seguir','Describe un lugar','Defiende una idea'], r: 1 },
      { p: '"El árbol lloraba" es:', ops: ['Metáfora','Símil','Personificación','Hipérbole'], r: 2 },
      { p: 'Texto que describe características:', ops: ['Narrativo','Descriptivo','Argumentativo','Expositivo'], r: 1 },
      { p: '"Por lo tanto" indica:', ops: ['Contraste','Adición','Consecuencia','Causa'], r: 2 },
      { p: 'Texto argumentativo busca:', ops: ['Entretener','Describir','Persuadir','Instruir'], r: 2 },
      { p: 'Un párrafo es:', ops: ['Una sola oración','Conjunto de oraciones con una idea','Todo el texto','El título'], r: 1 },
    ],
    2: [
      { p: 'Género para representarse en escena:', ops: ['Narrativo','Lírico','Dramático','Ensayístico'], r: 2 },
      { p: 'Autor de "Tradiciones Peruanas":', ops: ['César Vallejo','Ricardo Palma','Mario Vargas Llosa','José María Arguedas'], r: 1 },
      { p: '"Tus ojos son dos luceros" es:', ops: ['Símil','Metáfora','Hipérbole','Anáfora'], r: 1 },
      { p: 'Género que expresa sentimientos en verso:', ops: ['Narrativo','Lírico','Dramático','Ensayístico'], r: 1 },
      { p: 'La fábula pertenece al género:', ops: ['Dramático','Lírico','Narrativo','Ensayístico'], r: 2 },
      { p: 'César Vallejo escribió:', ops: ['La ciudad y los perros','Trilce','Tradiciones Peruanas','El zorro de arriba'], r: 1 },
      { p: 'Mario Vargas Llosa ganó el Nobel en:', ops: ['2005','2008','2010','2012'], r: 2 },
      { p: 'La tragedia es parte del género:', ops: ['Narrativo','Lírico','Dramático','Épico'], r: 2 },
      { p: '"La ciudad y los perros" es:', ops: ['Lírico','Dramático','Novela (narrativo)','Ensayo'], r: 2 },
      { p: 'La épica narra hazañas de:', ops: ['Seres cotidianos','Héroes y guerreros','Personajes cómicos','Animales'], r: 1 },
    ],
    3: [
      { p: '¿Qué parte de la oración expresa la acción?', ops: ['Sustantivo','Adjetivo','Verbo','Adverbio'], r: 2 },
      { p: 'Oración simple tiene:', ops: ['Dos verbos','Un verbo','Sin verbo','Tres cláusulas'], r: 1 },
      { p: 'Sujeto de una oración es:', ops: ['Lo que se dice del sustantivo','Quien realiza la acción','El complemento directo','El verbo principal'], r: 1 },
      { p: '¿Qué clase modifica al verbo?', ops: ['Adjetivo','Sustantivo','Adverbio','Preposición'], r: 2 },
      { p: 'Tilde diacrítica en "él" se usa cuando:', ops: ['Es artículo','Es pronombre personal','Siempre','Nunca'], r: 1 },
      { p: 'Función de la preposición:', ops: ['Nombrar','Calificar','Unir palabras indicando relación','Expresar acción'], r: 2 },
      { p: 'El predicado contiene:', ops: ['Solo el sujeto','Verbo y sus complementos','Solo adjetivos','La idea secundaria'], r: 1 },
      { p: 'En "Los niños jugaban felices", el adjetivo es:', ops: ['Los','niños','jugaban','felices'], r: 3 },
      { p: 'Núcleo del sujeto en "Los estudiantes estudian":', ops: ['Los','estudiantes','estudian','Los estudiantes'], r: 1 },
      { p: 'Oración compuesta tiene:', ops: ['Un solo verbo','Dos o más proposiciones','Sin verbo','Solo sustantivos'], r: 1 },
    ],
    4: [
      { p: 'Texto argumentativo incluye obligatoriamente:', ops: ['Personajes y trama','Tesis y argumentos','Pasos a seguir','Descripción de lugares'], r: 1 },
      { p: 'El ensayo es:', ops: ['Texto narrativo con personajes','Texto en prosa con tesis propia','Lista de instrucciones','Poema en prosa'], r: 1 },
      { p: 'Argumento de autoridad usa:', ops: ['Ejemplos cotidianos','Expertos o datos oficiales','Comparaciones','Emociones'], r: 1 },
      { p: '"Prosumidor" en comunicación digital:', ops: ['Solo productor','Solo consumidor','Produce y consume','Editor profesional'], r: 2 },
      { p: 'Estructura del ensayo:', ops: ['Inicio, nudo, desenlace','Intro, tesis, argumentos, conclusión','Solo tesis y conclusión','Párrafos sin orden'], r: 1 },
      { p: 'La publicidad busca principalmente:', ops: ['Informar eventos','Vender o promover','Narrar historias','Enseñar valores'], r: 1 },
      { p: 'Repetición al inicio de verso:', ops: ['Hipérbole','Anáfora','Metáfora','Ironía'], r: 1 },
      { p: 'Función del contraargumento:', ops: ['Apoyar la tesis','Refutar objeciones','Reemplazar la tesis','Sustituir la conclusión'], r: 1 },
      { p: 'Eslogan publicitario usa:', ops: ['Argumentos lógicos','Lenguaje conciso y memorable','Estadísticas detalladas','Textos largos'], r: 1 },
      { p: 'Análisis crítico de medios implica:', ops: ['Creer todo','Identificar emisor, propósito y recursos','Solo leer titulares','Rechazar toda información'], r: 1 },
    ],
    5: [
      { p: 'Lenguaje audiovisual combina:', ops: ['Solo audio','Solo visual','Imagen y sonido','Solo texto'], r: 2 },
      { p: 'Plano general muestra:', ops: ['Solo el rostro','Cuerpo completo y entorno','Un detalle','Solo los ojos'], r: 1 },
      { p: '"Fake news" son:', ops: ['Noticias extranjeras','Noticias antiguas','Noticias falsas o manipuladas','Noticias sin fuente'], r: 2 },
      { p: 'Ángulo contrapicado muestra al sujeto:', ops: ['Desde arriba','Desde abajo','De frente','De perfil'], r: 1 },
      { p: 'Proyecto de vida incluye:', ops: ['Solo objetivos económicos','Metas personales, profesionales y valores','Solo la carrera','Lista de actividades'], r: 1 },
      { p: 'El ciberacoso es:', ops: ['Jugar videojuegos','Acoso mediante plataformas digitales','Usar internet sin permiso','Crear contenido falso'], r: 1 },
      { p: 'Propaganda busca:', ops: ['Vender productos','Cambiar actitudes o comportamientos','Entretener','Informar objetivamente'], r: 1 },
      { p: 'Receptor activo en comunicación:', ops: ['Solo recibe','Interpreta, cuestiona y retroalimenta','Ignora el mensaje','Solo decodifica'], r: 1 },
      { p: 'Fact-checking sirve para:', ops: ['Crear noticias','Verificar información antes de publicar','Censurar medios','Escribir eslóganes'], r: 1 },
      { p: 'Planos de mayor a menor amplitud:', ops: ['PP → PM → PG','PG → PM → PP','PM → PG → PP','PP → PG → PM'], r: 1 },
    ],
  },
  ingles: {
    1: [
      { p: '"She ___ a student."', ops: ['am','is','are','be'], r: 1 },
      { p: '"Good morning" se usa:', ops: ['De noche','En la tarde','En la mañana','Al mediodía'], r: 2 },
      { p: '"Rojo" en inglés:', ops: ['Blue','Green','Red','Yellow'], r: 2 },
      { p: 'One, two, ___, four', ops: ['three','free','tree','thre'], r: 0 },
      { p: '"They ___ happy."', ops: ['is','am','are','be'], r: 2 },
      { p: 'Plural of "book":', ops: ['bookies','books','bookes','booksies'], r: 1 },
      { p: '"Goodbye" significa:', ops: ['Hola','Gracias','Adiós','Por favor'], r: 2 },
      { p: '"I ___ from Peru."', ops: ['is','am','are','be'], r: 1 },
      { p: 'Color del cielo en un día despejado:', ops: ['Red','Green','Blue','Yellow'], r: 2 },
      { p: 'Días de la semana en inglés son:', ops: ['5','6','7','8'], r: 2 },
    ],
    2: [
      { p: 'Pasado irregular de "go":', ops: ['goed','gone','went','goes'], r: 2 },
      { p: '"She ___ English every day."', ops: ['study','studys','studies','studied'], r: 2 },
      { p: '"Siempre" en inglés:', ops: ['never','sometimes','often','always'], r: 3 },
      { p: '"Do you like pizza?" → "Yes, I ___."', ops: ['do','does','am','like'], r: 0 },
      { p: 'Pasado de "eat":', ops: ['eated','ate','eaten','eats'], r: 1 },
      { p: '"Where ___ you live?"', ops: ['does','is','do','are'], r: 2 },
      { p: '"I ___ like coffee." (negativo)', ops: ['not','dont',"don't","doesn't"], r: 2 },
      { p: '"He ___ TV every night." (3rd person)', ops: ['watch','watchs','watches','watched'], r: 2 },
      { p: 'Expresión de tiempo para present simple:', ops: ['yesterday','last week','every day','two days ago'], r: 2 },
      { p: '"They ___ not at school today."', ops: ['is','am','are','be'], r: 2 },
    ],
    3: [
      { p: '"I ___ to the market yesterday." (go)', ops: ['go','goes','went','gone'], r: 2 },
      { p: 'Pasado de "buy":', ops: ['buyed','byed','bought','buys'], r: 2 },
      { p: '"Did you ___ breakfast?"', ops: ['ate','eat','eated','eating'], r: 1 },
      { p: 'Expresión de tiempo pasado:', ops: ['every day','tomorrow','yesterday','usually'], r: 2 },
      { p: 'Negativo pasado: "She ___ go."', ops: ['not did',"didn't","doesn't","isn't"], r: 1 },
      { p: 'Pasado de "see":', ops: ['sawed','seed','seen','saw'], r: 3 },
      { p: '"They ___ a great movie last night."', ops: ['watch','watches','watched','are watching'], r: 2 },
      { p: '"Was/were" es pasado de:', ops: ['do','have','be','go'], r: 2 },
      { p: '"___ you study last night?"', ops: ['Do','Does','Did','Were'], r: 2 },
      { p: 'Pasado de "have":', ops: ['haved','have','had','has'], r: 2 },
    ],
    4: [
      { p: '"I ___ visit Paris, I already have tickets."', ops: ['will','am going to','would','should'], r: 1 },
      { p: '"If you study, you ___ pass."', ops: ['would','will','might','should'], r: 1 },
      { p: '"You ___ see a doctor." (consejo)', ops: ['must','can','should','will'], r: 2 },
      { p: '"She ___ swim very well." (habilidad)', ops: ['must','can','should','will'], r: 1 },
      { p: 'Modal de obligación fuerte:', ops: ['can','should','must','would'], r: 2 },
      { p: '"It ___ rain tomorrow." (predicción espontánea)', ops: ['going to','will','must','should'], r: 1 },
      { p: '"If it rains, we ___ stay home."', ops: ['would','will','might','should'], r: 1 },
      { p: '"___ I open the window?" (permiso)', ops: ['Must','Should','May','Will'], r: 2 },
      { p: '"I ___ help you." (oferta)', ops: ['must','should','will','can'], r: 2 },
      { p: '"Going to" se usa para:', ops: ['Decisiones espontáneas','Planes ya decididos','Predicciones sin evidencia','Obligaciones'], r: 1 },
    ],
    5: [
      { p: '"I have visited Paris." es:', ops: ['Past simple','Present perfect','Future simple','Present continuous'], r: 1 },
      { p: '"They build houses." → Passive:', ops: ['Houses built.','Houses are built.','They are built.','Houses were built.'], r: 1 },
      { p: '"The student ___ won the prize is from Lima."', ops: ['which','where','who','whom'], r: 2 },
      { p: '"I have ___ finished." (keyword)', ops: ['ago','last','just','yesterday'], r: 2 },
      { p: '"The book ___ written by Vargas Llosa."', ops: ['is','was','were','be'], r: 1 },
      { p: '"Lima, ___ is the capital, is beautiful."', ops: ['who','where','which','that'], r: 2 },
      { p: '"She has lived here ___ 2010."', ops: ['for','since','ago','until'], r: 1 },
      { p: '"Have you ___ visited Machu Picchu?"', ops: ['always','never','ever','just'], r: 2 },
      { p: '"Houses ___ built every year." (presente pasiva)', ops: ['is','are','were','was'], r: 1 },
      { p: 'Present perfect con "for" indica:', ops: ['Fecha específica','Duración de tiempo','Experiencia de vida','Acción reciente'], r: 1 },
    ],
  },
};

// ── Flashcards Inglés por grado ─────────────────────
const FLASHCARDS = {
  1: [
    { f: 'Hello / Hi', b: 'Hola (informal)', ex: '"Hello! My name is Ana."' },
    { f: 'What is your name?', b: '¿Cómo te llamas?', ex: '"My name is Carlos."' },
    { f: 'How old are you?', b: '¿Cuántos años tienes?', ex: '"I am 12 years old."' },
    { f: 'Where are you from?', b: '¿De dónde eres?', ex: '"I am from Peru."' },
    { f: 'This is a book.', b: 'Esto es un libro.', ex: '"This is a pencil."' },
    { f: 'red / blue / green', b: 'rojo / azul / verde', ex: '"The apple is red."' },
    { f: 'one, two, three...', b: 'uno, dos, tres...', ex: '"I have three brothers."' },
    { f: 'Monday, Tuesday...', b: 'Lunes, Martes...', ex: '"Today is Monday."' },
  ],
  2: [
    { f: 'I wake up at 6 AM.', b: 'Me despierto a las 6 AM.', ex: '"She wakes up early every day."' },
    { f: 'always / usually / sometimes', b: 'siempre / generalmente / a veces', ex: '"I always brush my teeth."' },
    { f: 'do / does / don\'t / doesn\'t', b: 'auxiliares del present simple', ex: '"Does she study English?"' },
    { f: 'go → went', b: 'ir → fui/fue', ex: '"I went to school yesterday."' },
    { f: 'eat → ate', b: 'comer → comí/comió', ex: '"She ate pizza last night."' },
    { f: 'have → had', b: 'tener → tuve/tuvo', ex: '"We had a great time."' },
    { f: 'in / on / at (time)', b: 'Preposiciones de tiempo', ex: '"I study at night."' },
    { f: 'How often do you...?', b: '¿Con qué frecuencia...?', ex: '"How often do you exercise?"' },
  ],
  3: [
    { f: 'walked / talked / played', b: 'Pasado regular: +ed', ex: '"They played football yesterday."' },
    { f: 'see → saw', b: 'ver → vi/vio', ex: '"I saw a great movie."' },
    { f: 'buy → bought', b: 'comprar → compré/compró', ex: '"She bought new shoes."' },
    { f: 'take → took', b: 'tomar → tomó/tomé', ex: '"He took the bus."' },
    { f: 'make → made', b: 'hacer → hizo/hice', ex: '"They made a cake."' },
    { f: 'last week / ago / yesterday', b: 'Expresiones de tiempo pasado', ex: '"Two days ago I visited my grandma."' },
    { f: 'was / were', b: 'Pasado de "to be"', ex: '"She was happy. They were tired."' },
    { f: 'Did + verb base', b: 'Pregunta en pasado simple', ex: '"Did you eat breakfast?"' },
  ],
  4: [
    { f: 'will + verb', b: 'Futuro (decisión espontánea)', ex: '"I will help you with that."' },
    { f: 'am/is/are going to', b: 'Planes ya decididos', ex: '"I\'m going to study abroad."' },
    { f: 'can / could', b: 'Habilidad presente/pasado', ex: '"She can speak three languages."' },
    { f: 'should', b: 'Consejo o recomendación', ex: '"You should sleep early."' },
    { f: 'must', b: 'Obligación fuerte', ex: '"You must wear a seatbelt."' },
    { f: 'If + present, will + verb', b: 'Condicional tipo 1', ex: '"If you study, you will pass."' },
    { f: 'may / might', b: 'Posibilidad', ex: '"It might rain tomorrow."' },
    { f: 'would like', b: 'Querer educadamente', ex: '"I would like a glass of water."' },
  ],
  5: [
    { f: 'have/has + past participle', b: 'Present perfect', ex: '"I have visited Machu Picchu."' },
    { f: 'ever / never / just / already / yet', b: 'Keywords del present perfect', ex: '"Have you ever eaten ceviche?"' },
    { f: 'to be + past participle', b: 'Voz pasiva', ex: '"The book was written by Vargas Llosa."' },
    { f: 'who / which / where', b: 'Pronombres relativos', ex: '"The girl who won is from Cusco."' },
    { f: 'since / for', b: 'Desde / hace (con perfect)', ex: '"I have lived here since 2010."' },
    { f: 'Defining vs non-defining clause', b: 'Relativas definidas vs no definidas', ex: '"Lima, which is the capital, is big."' },
    { f: 'been vs gone', b: 'visitado y regresado vs fue y no volvió', ex: '"She has been to Paris."' },
    { f: 'am/is/are + pp (passive)', b: 'Voz pasiva presente', ex: '"Houses are built every year."' },
  ],
};

// ── Fórmulas Matemática por grado ───────────────────
const FORMULAS = {
  1: [
    { partes: ['Área rectángulo = base × ', '____'], r: 'altura', pista: 'A = b × ?' },
    { partes: ['MCM: factores primos con mayor ', '____'], r: 'exponente', pista: 'mayor ...' },
    { partes: ['Porcentaje = (parte ÷ ', '____ ) × 100'], r: 'total', pista: '(p÷?)×100' },
    { partes: ['Fracción = Numerador ÷ ', '____'], r: 'Denominador', pista: 'a ÷ ?' },
  ],
  2: [
    { partes: ['ax + b = 0  →  x = −b ÷ ', '____'], r: 'a', pista: 'x=−b/?' },
    { partes: ['(a + b)² = a² + 2ab + ', '____'], r: 'b²', pista: '...+?' },
    { partes: ['a² − b² = (a+b)(a', '____', ')'], r: '−b', pista: '(a+b)(a?)' },
    { partes: ['Pendiente m = Δy ÷ ', '____'], r: 'Δx', pista: 'm=Δy÷?' },
  ],
  3: [
    { partes: ['Pitágoras: c² = a² + ', '____'], r: 'b²', pista: 'c²=a²+?' },
    { partes: ['sen θ = opuesto ÷ ', '____'], r: 'hipotenusa', pista: 'SOH' },
    { partes: ['Área triángulo = (base × altura) ÷ ', '____'], r: '2', pista: '(b×h)÷?' },
    { partes: ['cos θ = adyacente ÷ ', '____'], r: 'hipotenusa', pista: 'CAH' },
  ],
  4: [
    { partes: ['Media = Σx ÷ ', '____'], r: 'n', pista: 'suma÷?' },
    { partes: ['P(A) = favorables ÷ ', '____'], r: 'posibles', pista: 'P=fav÷?' },
    { partes: ['f(x) = ', '____', 'x + b  (pendiente)'], r: 'm', pista: 'f(x)=?x+b' },
    { partes: ['Varianza = Σ(xi − x̄)² ÷ ', '____'], r: 'n', pista: 'Σ(...)÷?' },
  ],
  5: [
    { partes: ["d/dx(xⁿ) = ", "____", "·xⁿ⁻¹"], r: 'n', pista: '?·xⁿ⁻¹' },
    { partes: ['∫xⁿ dx = xⁿ⁺¹ ÷ (n+1) + ', '____'], r: 'C', pista: '...+?' },
    { partes: ['|v| = √(x² + ', '____', ')'], r: 'y²', pista: '√(x²+?)' },
    { partes: ["f'(x) de 3x² + 2x = ", "____"], r: '6x + 2', pista: '6x+?' },
  ],
};

// ── Verdadero / Falso (ciencia e historia) ──────────
const VF = {
  ciencia: {
    1: [
      { s: 'Las plantas producen O₂ en la fotosíntesis.', r: true },
      { s: 'Las bacterias son células eucariotas.', r: false },
      { s: 'La mitocondria produce energía en la célula.', r: true },
      { s: 'El ecosistema solo incluye seres vivos.', r: false },
      { s: 'El sistema circulatorio transporta sangre.', r: true },
    ],
    2: [
      { s: 'El número atómico indica la cantidad de protones.', r: true },
      { s: 'El pH mide la temperatura de una solución.', r: false },
      { s: 'Los gases nobles son muy reactivos.', r: false },
      { s: 'El agua tiene fórmula H₂O.', r: true },
      { s: 'La neutralización produce sal y agua.', r: true },
    ],
    3: [
      { s: 'En MRU la velocidad es constante.', r: true },
      { s: 'F = m × a es la Primera Ley de Newton.', r: false },
      { s: 'La energía cinética es Ec = ½mv².', r: true },
      { s: 'La luz es una onda mecánica.', r: false },
      { s: 'El trabajo se calcula con W = F × d.', r: true },
    ],
    4: [
      { s: 'Los alcanos tienen doble enlace C=C.', r: false },
      { s: 'El reactivo limitante se agota primero.', r: true },
      { s: 'Los alcoholes tienen grupo funcional −OH.', r: true },
      { s: 'La estequiometría calcula cantidades en reacciones.', r: true },
      { s: 'Los alquenos tienen fórmula CₙH₂ₙ₊₂.', r: false },
    ],
    5: [
      { s: 'E = mc² es la equivalencia masa-energía.', r: true },
      { s: 'El Sistema Solar tiene 9 planetas.', r: false },
      { s: 'La fisión divide núcleos pesados.', r: true },
      { s: 'La velocidad de la luz es 3×10⁸ m/s.', r: true },
      { s: 'La fusión nuclear es la misma que una reacción química.', r: false },
    ],
  },
  historia: {
    1: [
      { s: 'Egipto se desarrolló en torno al río Nilo.', r: true },
      { s: 'La democracia fue inventada en Roma.', r: false },
      { s: 'El Perú tiene 3 regiones naturales.', r: true },
      { s: 'Mesopotamia fue cuna de la escritura cuneiforme.', r: true },
      { s: 'El Perú tiene 20 departamentos.', r: false },
    ],
    2: [
      { s: 'La capital del Imperio Inca fue Cusco.', r: true },
      { s: 'Francisco Pizarro llegó al Perú en 1532.', r: true },
      { s: 'El Tahuantinsuyo tenía 3 suyos.', r: false },
      { s: 'La mita era un trabajo forzado en el Virreinato.', r: true },
      { s: 'El Virreinato del Perú fue creado en 1532.', r: false },
    ],
    3: [
      { s: 'La independencia del Perú fue en 1821.', r: true },
      { s: 'San Martín completó la independencia sudamericana.', r: false },
      { s: 'La Batalla de Ayacucho fue en 1824.', r: true },
      { s: 'La rebelión de Túpac Amaru II fue en 1780.', r: true },
      { s: 'El Perú adoptó una monarquía tras la independencia.', r: false },
    ],
    4: [
      { s: 'El APRA fue fundado en 1924.', r: true },
      { s: 'Velasco realizó la Reforma Agraria en 1975.', r: false },
      { s: 'Fujimori capturó a Abimael Guzmán en 1992.', r: true },
      { s: 'Sendero Luminoso inició en 1978.', r: false },
      { s: 'El Oncenio fue el gobierno de Leguía.', r: true },
    ],
    5: [
      { s: 'El Muro de Berlín cayó en 1989.', r: true },
      { s: 'La ONU fue fundada en 1939.', r: false },
      { s: 'La Guerra Fría fue entre EE.UU. y la URSS.', r: true },
      { s: 'La URSS se disolvió en 1989.', r: false },
      { s: 'Perú pertenece a la Alianza del Pacífico.', r: true },
    ],
  },
};

// ── Ordenar pasos (ciencia e historia) ──────────────
const ORDENAR = {
  ciencia: {
    1: { en: 'Ordena los pasos de la FOTOSÍNTESIS:', items: ['Los cloroplastos captan la luz solar','La planta absorbe CO₂ y H₂O','Se produce glucosa y O₂','La glucosa se usa como energía'], ok: ['La planta absorbe CO₂ y H₂O','Los cloroplastos captan la luz solar','Se produce glucosa y O₂','La glucosa se usa como energía'] },
    2: { en: 'Ordena los pasos del MÉTODO CIENTÍFICO:', items: ['Análisis y conclusión','Observación del fenómeno','Experimentación','Formulación de hipótesis'], ok: ['Observación del fenómeno','Formulación de hipótesis','Experimentación','Análisis y conclusión'] },
    3: { en: 'Ordena el MOVIMIENTO UNIFORMEMENTE ACELERADO:', items: ['Calcular distancia: d=v₀t+½at²','Medir velocidad inicial v₀','Calcular aceleración: a=(v−v₀)/t','Medir velocidad final v'], ok: ['Medir velocidad inicial v₀','Medir velocidad final v','Calcular aceleración: a=(v−v₀)/t','Calcular distancia: d=v₀t+½at²'] },
    4: { en: 'Ordena una REACCIÓN QUÍMICA de síntesis:', items: ['Balancear la ecuación','Identificar los reactivos','Verificar conservación de la masa','Escribir los productos'], ok: ['Identificar los reactivos','Escribir los productos','Balancear la ecuación','Verificar conservación de la masa'] },
    5: { en: 'Ordena el CICLO DE VIDA DE UNA ESTRELLA tipo Sol:', items: ['Gigante roja','Nebulosa solar','Enana blanca','Estrella de secuencia principal'], ok: ['Nebulosa solar','Estrella de secuencia principal','Gigante roja','Enana blanca'] },
  },
  historia: {
    1: { en: 'Ordena del más antiguo al más reciente:', items: ['Civilización griega (~800 a.C.)','Imperio Romano (~27 a.C.)','Mesopotamia (~3500 a.C.)','Egipto antiguo (~3100 a.C.)'], ok: ['Mesopotamia (~3500 a.C.)','Egipto antiguo (~3100 a.C.)','Civilización griega (~800 a.C.)','Imperio Romano (~27 a.C.)'] },
    2: { en: 'Ordena estos eventos del PERÚ PREHISPÁNICO e COLONIAL:', items: ['Lima fundada (1535)','El Virreinato (1542)','El Tahuantinsuyo (1438)','La Conquista (1532)'], ok: ['El Tahuantinsuyo (1438)','La Conquista (1532)','Lima fundada (1535)','El Virreinato (1542)'] },
    3: { en: 'Ordena el PROCESO DE INDEPENDENCIA:', items: ['Batalla de Ayacucho (1824)','Llegada de San Martín (1820)','Rebelión de Túpac Amaru II (1780)','Proclamación de independencia (1821)'], ok: ['Rebelión de Túpac Amaru II (1780)','Llegada de San Martín (1820)','Proclamación de independencia (1821)','Batalla de Ayacucho (1824)'] },
    4: { en: 'Ordena estos eventos del SIGLO XX PERUANO:', items: ['Captura de Guzmán (1992)','Inicio de Sendero Luminoso (1980)','Reforma Agraria de Velasco (1969)','Fundación del APRA (1924)'], ok: ['Fundación del APRA (1924)','Reforma Agraria de Velasco (1969)','Inicio de Sendero Luminoso (1980)','Captura de Guzmán (1992)'] },
    5: { en: 'Ordena estos eventos CONTEMPORÁNEOS:', items: ['Disolución de la URSS (1991)','Caída del Muro de Berlín (1989)','Inicio de la 2da Guerra Mundial (1939)','Fundación de la ONU (1945)'], ok: ['Inicio de la 2da Guerra Mundial (1939)','Fundación de la ONU (1945)','Caída del Muro de Berlín (1989)','Disolución de la URSS (1991)'] },
  },
};
